// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnNYEZEjSVzN0ONSCVBeW-EWSzR5Ps1I',
    appId: '1:726845973497:web:529961f106aefd1a085328',
    messagingSenderId: '726845973497',
    projectId: 'e-commerce-app-flutter-d1d09',
    authDomain: 'e-commerce-app-flutter-d1d09.firebaseapp.com',
    storageBucket: 'e-commerce-app-flutter-d1d09.firebasestorage.app',
    measurementId: 'G-GM36ZJV9KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQ37dN-jr1f1eya2QIwvrdy25nFOsYCw',
    appId: '1:726845973497:android:068eba89018b5021085328',
    messagingSenderId: '726845973497',
    projectId: 'e-commerce-app-flutter-d1d09',
    storageBucket: 'e-commerce-app-flutter-d1d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZR1ytX8ZzedbmSDeKV4DEJxvdM6Yrpc',
    appId: '1:726845973497:ios:b88816516b38c0b2085328',
    messagingSenderId: '726845973497',
    projectId: 'e-commerce-app-flutter-d1d09',
    storageBucket: 'e-commerce-app-flutter-d1d09.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcZR1ytX8ZzedbmSDeKV4DEJxvdM6Yrpc',
    appId: '1:726845973497:ios:b88816516b38c0b2085328',
    messagingSenderId: '726845973497',
    projectId: 'e-commerce-app-flutter-d1d09',
    storageBucket: 'e-commerce-app-flutter-d1d09.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnNYEZEjSVzN0ONSCVBeW-EWSzR5Ps1I',
    appId: '1:726845973497:web:ea92004017edf3b7085328',
    messagingSenderId: '726845973497',
    projectId: 'e-commerce-app-flutter-d1d09',
    authDomain: 'e-commerce-app-flutter-d1d09.firebaseapp.com',
    storageBucket: 'e-commerce-app-flutter-d1d09.firebasestorage.app',
    measurementId: 'G-7V1E7N39WE',
  );
}
